//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anpham_phieumuonAP
    {
        public int MaAnPham { get; set; }
        public int MaPhieuMuonAP { get; set; }
    
        public virtual anpham anpham { get; set; }
    }
}
