//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dausach
    {
        public dausach()
        {
            this.saches = new HashSet<sach>();
            this.tacgias = new HashSet<tacgia>();
        }
    
        public int MaDauSach { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public string NgonNgu { get; set; }
        public Nullable<int> MaLinhVuc { get; set; }
        public string ISBN { get; set; }
        public string NhanDeChinh { get; set; }
        public string NhanDeSongSong { get; set; }
        public string NhanDeKhac { get; set; }
        public string NamXuatBan { get; set; }
        public string BanQuyen { get; set; }
        public Nullable<double> GiaTien { get; set; }
    
        public virtual linhvuc linhvuc { get; set; }
        public virtual nhaxuatban nhaxuatban { get; set; }
        public virtual ICollection<sach> saches { get; set; }
        public virtual ICollection<tacgia> tacgias { get; set; }
    }
}
