//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class docgia
    {
        public docgia()
        {
            this.phieumuonAPs = new HashSet<phieumuonAP>();
            this.phieumuonsaches = new HashSet<phieumuonsach>();
            this.phieuphatAPs = new HashSet<phieuphatAP>();
            this.phieuphatsaches = new HashSet<phieuphatsach>();
        }
    
        public int MaDocGia { get; set; }
        public string MaThe { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string GioiTinh { get; set; }
        public string Email { get; set; }
        public string SoDT { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<int> TaiKhoan { get; set; }
        public Nullable<int> LoaiDocGia { get; set; }
        public string AnhDocGia { get; set; }
    
        public virtual loaidocgia loaidocgia1 { get; set; }
        public virtual taikhoan taikhoan1 { get; set; }
        public virtual ICollection<phieumuonAP> phieumuonAPs { get; set; }
        public virtual ICollection<phieumuonsach> phieumuonsaches { get; set; }
        public virtual ICollection<phieuphatAP> phieuphatAPs { get; set; }
        public virtual ICollection<phieuphatsach> phieuphatsaches { get; set; }
    }
}
