//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaidocgia
    {
        public loaidocgia()
        {
            this.docgias = new HashSet<docgia>();
        }
    
        public int MaLoaiDocGia { get; set; }
        public string TenLoaiDocGia { get; set; }
        public Nullable<int> SoSachDaMuon { get; set; }
        public Nullable<int> ThoiGianMuon { get; set; }
        public Nullable<int> SoLanDuocGiaHan { get; set; }
        public Nullable<double> TienPhat { get; set; }
    
        public virtual ICollection<docgia> docgias { get; set; }
    }
}
