//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhaxuatban
    {
        public nhaxuatban()
        {
            this.anphams = new HashSet<anpham>();
            this.dausaches = new HashSet<dausach>();
        }
    
        public int MaNXB { get; set; }
        public string TenNXB { get; set; }
        public string DiaChi { get; set; }
        public string SoĐT { get; set; }
        public string email { get; set; }
        public string website { get; set; }
    
        public virtual ICollection<anpham> anphams { get; set; }
        public virtual ICollection<dausach> dausaches { get; set; }
    }
}
