//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sach
    {
        public sach()
        {
            this.sach_phieumuonsach = new HashSet<sach_phieumuonsach>();
        }
    
        public int id { get; set; }
        public string MaCaBiet { get; set; }
        public Nullable<int> LanTaiBan { get; set; }
        public Nullable<int> MaDauSach { get; set; }
    
        public virtual dausach dausach { get; set; }
        public virtual ICollection<sach_phieumuonsach> sach_phieumuonsach { get; set; }
    }
}
