//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taikhoan
    {
        public taikhoan()
        {
            this.docgias = new HashSet<docgia>();
            this.nhanviens = new HashSet<nhanvien>();
        }
    
        public int MaTaiKhoan { get; set; }
        public string Username { get; set; }
        public string pass { get; set; }
        public Nullable<int> LoaiTaiKhoan { get; set; }
    
        public virtual ICollection<docgia> docgias { get; set; }
        public virtual ICollection<nhanvien> nhanviens { get; set; }
    }
}
